//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaconReceiverXamarin.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeaconReceiverXamarin.Resource.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -40 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string allowed_min_rssi_max {
            get {
                return ResourceManager.GetString("allowed_min_rssi_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -120 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string allowed_min_rssi_min {
            get {
                return ResourceManager.GetString("allowed_min_rssi_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   86400 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string analysis_interval_max {
            get {
                return ResourceManager.GetString("analysis_interval_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string analysis_interval_min {
            get {
                return ResourceManager.GetString("analysis_interval_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EverytimeReloadLocalSettingEnable {
            get {
                return ResourceManager.GetString("EverytimeReloadLocalSettingEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monitoring に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string monitoring {
            get {
                return ResourceManager.GetString("monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の値が不正です。設定内容を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msg_error_illegal_settings {
            get {
                return ResourceManager.GetString("msg_error_illegal_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IoTHubの認証に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msg_error_iothub_auth_failure {
            get {
                return ResourceManager.GetString("msg_error_iothub_auth_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IoTHubに接続できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msg_error_iothub_connection_failure {
            get {
                return ResourceManager.GetString("msg_error_iothub_connection_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error initializing MQTT connection:接続する権限がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msg_error_iothub_sdk_auth_failure {
            get {
                return ResourceManager.GetString("msg_error_iothub_sdk_auth_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   86400 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string send_interval_max {
            get {
                return ResourceManager.GetString("send_interval_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string send_interval_min {
            get {
                return ResourceManager.GetString("send_interval_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   active_host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_active_host_key {
            get {
                return ResourceManager.GetString("setting_active_host_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   allowed_min_rssi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_allowed_min_rssi_key {
            get {
                return ResourceManager.GetString("setting_allowed_min_rssi_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   analysis_interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_analysis_interval_key {
            get {
                return ResourceManager.GetString("setting_analysis_interval_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分析間隔［秒］ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_analysis_interval_label {
            get {
                return ResourceManager.GetString("setting_analysis_interval_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   customer_front_auth_info_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_customer_front_auth_info_id_key {
            get {
                return ResourceManager.GetString("setting_customer_front_auth_info_id_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   customer_front_auth_info_password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_customer_front_auth_info_password_key {
            get {
                return ResourceManager.GetString("setting_customer_front_auth_info_password_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   customer_front_url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_customer_front_url_key {
            get {
                return ResourceManager.GetString("setting_customer_front_url_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failback に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_failback_key {
            get {
                return ResourceManager.GetString("setting_failback_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failover に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_failover_key {
            get {
                return ResourceManager.GetString("setting_failover_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iothub_auth_info_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_iothub_auth_info_name_key {
            get {
                return ResourceManager.GetString("setting_iothub_auth_info_name_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iothub_auth_info_password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_iothub_auth_info_password_key {
            get {
                return ResourceManager.GetString("setting_iothub_auth_info_password_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_receiver_identifier_max_Length {
            get {
                return ResourceManager.GetString("setting_receiver_identifier_max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   receiver_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_receiver_name_key {
            get {
                return ResourceManager.GetString("setting_receiver_name_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   receiver_nickname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_receiver_nickname_key {
            get {
                return ResourceManager.GetString("setting_receiver_nickname_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rssi_type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_rssi_type_key {
            get {
                return ResourceManager.GetString("setting_rssi_type_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   send_interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_send_interval_key {
            get {
                return ResourceManager.GetString("setting_send_interval_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信間隔［秒］ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_send_interval_label {
            get {
                return ResourceManager.GetString("setting_send_interval_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   standby_host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_standby_host_key {
            get {
                return ResourceManager.GetString("setting_standby_host_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   uuid_white_list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_uuid_white_list_key {
            get {
                return ResourceManager.GetString("setting_uuid_white_list_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   web_settings_url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting_web_settings_url_key {
            get {
                return ResourceManager.GetString("setting_web_settings_url_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebSettingsDownloadEnable {
            get {
                return ResourceManager.GetString("WebSettingsDownloadEnable", resourceCulture);
            }
        }
    }
}
